// CPP Program to find quotient and remainder;
#include<iostream.h>
#include<conio.h>

int main()
{
 clrscr();
 int a,b;
 cout<<"Enter any two numbers for division"<<endl;
 cout<<"First enter Divident, then Diviser"<<endl;
 cin>>a>>b;
 cout<<"The Quotient is: "<<a/b<<endl;
 cout<<"and the Remainder is: "<<a%b;
 getch();
}

/*OUTPUT

Enter any two numbers for division
First enter Divident, then Diviser
5
2
The Quotient is: 2
and the Remainder is: 1
*/
