//CPP Program for find size of different datatypes;
#include<iostream.h>
#include<conio.h>

void main()
{
 clrscr();
 cout<<"The size of char(Character) Datatype is: "<<sizeof(char)<<endl;
 cout<<"The size of int(Integer) Datatype is: "<<sizeof(int)<<endl;
 cout<<"The size of float Datatype is: "<<sizeof(float)<<endl;
 getch();
}
/* OUTPUT
The size of char(Character) Datatype is: 1
The size of int(Integer) Datatype is: 2
The size of float Datatype is: 4
*/
